export const ADDTOCART_START = "ADDTOCART_START";
export const ADDTOCART_SUCCESS = 'ADDTOCART_SUCCESS';

export const REMOVETOCART_START = "REMOVETOCART_START";
export const REMOVETOCART_SUCCESS = 'REMOVETOCART_SUCCESS';

