export const ADD_CUSTOMER_START = 'ADD_CUSTOMER_START';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';

export const UPDATE_CUSTOMER_START = 'UPDATE_CUSTOMER_START';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';

export const DELETE_CUSTOMER_START = 'DELETE_CUSTOMER_START';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';

